//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFunc.UnitConverters.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xFunc.UnitConverters.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   エーカー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Acres {
            get {
                return ResourceManager.GetString("Acres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   面積 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaConverterName {
            get {
                return ResourceManager.GetString("AreaConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   天文単位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AstronomicalUnits {
            get {
                return ResourceManager.GetString("AstronomicalUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   摂氏 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センチメートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Centimeters {
            get {
                return ResourceManager.GetString("Centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェーン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Chains {
            get {
                return ResourceManager.GetString("Chains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   立方センチメートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CubicCentimeters {
            get {
                return ResourceManager.GetString("CubicCentimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   立方フィート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CubicFeet {
            get {
                return ResourceManager.GetString("CubicFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   立方インチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CubicInches {
            get {
                return ResourceManager.GetString("CubicInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   立方メートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CubicMeters {
            get {
                return ResourceManager.GetString("CubicMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   立方ヤード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CubicYards {
            get {
                return ResourceManager.GetString("CubicYards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドリール度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Delisle {
            get {
                return ResourceManager.GetString("Delisle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   華氏 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファゾム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fathoms {
            get {
                return ResourceManager.GetString("Fathoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ガロン (UK) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GallonsUK {
            get {
                return ResourceManager.GetString("GallonsUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ガロン (US) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GallonsUS {
            get {
                return ResourceManager.GetString("GallonsUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グラム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Grams {
            get {
                return ResourceManager.GetString("Grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘクタール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hectares {
            get {
                return ResourceManager.GetString("Hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   馬力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Horsepower {
            get {
                return ResourceManager.GetString("Horsepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケルビン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キログラム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Kilograms {
            get {
                return ResourceManager.GetString("Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キロメートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キロワット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Kilowatts {
            get {
                return ResourceManager.GetString("Kilowatts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LengthConverterName {
            get {
                return ResourceManager.GetString("LengthConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   光年 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LightYears {
            get {
                return ResourceManager.GetString("LightYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リットル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Litres {
            get {
                return ResourceManager.GetString("Litres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   質量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MassConverterName {
            get {
                return ResourceManager.GetString("MassConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Metres {
            get {
                return ResourceManager.GetString("Metres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイクロメートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Micrometers {
            get {
                return ResourceManager.GetString("Micrometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイクロ秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Microseconds {
            get {
                return ResourceManager.GetString("Microseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ミリグラム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Milligrams {
            get {
                return ResourceManager.GetString("Milligrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ミリメートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Millimeters {
            get {
                return ResourceManager.GetString("Millimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ミリ秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ナノメートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Nanometres {
            get {
                return ResourceManager.GetString("Nanometres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   海里 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NauticalMiles {
            get {
                return ResourceManager.GetString("NauticalMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ニュートン度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Newton {
            get {
                return ResourceManager.GetString("Newton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーセク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Parsecs {
            get {
                return ResourceManager.GetString("Parsecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パイント (UK) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PintsUK {
            get {
                return ResourceManager.GetString("PintsUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パイント (US) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PintsUS {
            get {
                return ResourceManager.GetString("PintsUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pounds {
            get {
                return ResourceManager.GetString("Pounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕事率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PowerConverterName {
            get {
                return ResourceManager.GetString("PowerConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランキン度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rankine {
            get {
                return ResourceManager.GetString("Rankine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レオミュール度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Réaumur {
            get {
                return ResourceManager.GetString("Réaumur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロッド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rods {
            get {
                return ResourceManager.GetString("Rods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レーマー度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rømer {
            get {
                return ResourceManager.GetString("Rømer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Slugs {
            get {
                return ResourceManager.GetString("Slugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平方センチメートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SquareCentimeters {
            get {
                return ResourceManager.GetString("SquareCentimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平方フィート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SquareFeet {
            get {
                return ResourceManager.GetString("SquareFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平方インチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SquareInches {
            get {
                return ResourceManager.GetString("SquareInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平方キロメートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SquareKilometers {
            get {
                return ResourceManager.GetString("SquareKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平方メートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SquareMetres {
            get {
                return ResourceManager.GetString("SquareMetres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平方マイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SquareMiles {
            get {
                return ResourceManager.GetString("SquareMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平方ミリメートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SquareMillimeters {
            get {
                return ResourceManager.GetString("SquareMillimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平方ヤード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SquareYards {
            get {
                return ResourceManager.GetString("SquareYards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   温度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemperatureConverterName {
            get {
                return ResourceManager.GetString("TemperatureConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimeConverterName {
            get {
                return ResourceManager.GetString("TimeConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tonne {
            get {
                return ResourceManager.GetString("Tonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   体積 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VolumeConverterName {
            get {
                return ResourceManager.GetString("VolumeConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Watts {
            get {
                return ResourceManager.GetString("Watts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   週 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヤード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Yards {
            get {
                return ResourceManager.GetString("Yards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   年 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
