//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFunc.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xFunc.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   xFuncについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutButtonHeader {
            get {
                return ResourceManager.GetString("AboutButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   xFuncについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutButtonToolTip {
            get {
                return ResourceManager.GetString("AboutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   xFuncについて (F1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutToolTipTitle {
            get {
                return ResourceManager.GetString("AboutToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   xFuncについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   絶対値. 例: abs(-1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AbsToolTip {
            get {
                return ResourceManager.GetString("AbsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された値を加算. 例: x += 2. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddAssignToolTip {
            get {
                return ResourceManager.GetString("AddAssignToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddFuncCancel {
            get {
                return ResourceManager.GetString("AddFuncCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関数名が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddFuncError {
            get {
                return ResourceManager.GetString("AddFuncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Function: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddFuncFunc {
            get {
                return ResourceManager.GetString("AddFuncFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddFuncName {
            get {
                return ResourceManager.GetString("AddFuncName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddFuncOk {
            get {
                return ResourceManager.GetString("AddFuncOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規関数の追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddFuncTitle {
            get {
                return ResourceManager.GetString("AddFuncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdditionalLogicExpanderHeader {
            get {
                return ResourceManager.GetString("AdditionalLogicExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdditionalMathExpanderHeader {
            get {
                return ResourceManager.GetString("AdditionalMathExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddVarCancel {
            get {
                return ResourceManager.GetString("AddVarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddVarName {
            get {
                return ResourceManager.GetString("AddVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddVarOK {
            get {
                return ResourceManager.GetString("AddVarOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込み専用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddVarReadOnly {
            get {
                return ResourceManager.GetString("AddVarReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しい変数を追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddVarTitle {
            get {
                return ResourceManager.GetString("AddVarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Value: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddVarValue {
            get {
                return ResourceManager.GetString("AddVarValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビットAND演算子. 有理数は小数点以下切り捨て. 例: x and y, x &amp; y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AndToolTip {
            get {
                return ResourceManager.GetString("AndToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AnglesGroupHeader {
            get {
                return ResourceManager.GetString("AnglesGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AnswerBaseGroupHeader {
            get {
                return ResourceManager.GetString("AnswerBaseGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AnswerTextBox {
            get {
                return ResourceManager.GetString("AnswerTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   arccsc. 例: arccsc(90) or arccosec(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArccosecantToolTip {
            get {
                return ResourceManager.GetString("ArccosecantToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   arccos. 例. Example: arccos(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArccosineToolTip {
            get {
                return ResourceManager.GetString("ArccosineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   arccot. 例. Example: arccot(90) or arcctg(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArccotangentToolTip {
            get {
                return ResourceManager.GetString("ArccotangentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   arcosh. 例: arcosh(90) or arch(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcoshToolTip {
            get {
                return ResourceManager.GetString("ArcoshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   arcoth. 例: arcoth(90) or arcth(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcothToolTip {
            get {
                return ResourceManager.GetString("ArcothToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   arcsch. 例: arcsch(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcschToolTip {
            get {
                return ResourceManager.GetString("ArcschToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   arcsec. 例: arcsec(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcsecantToolTip {
            get {
                return ResourceManager.GetString("ArcsecantToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   arcsin. 例: arcsin(1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArcsineToolTip {
            get {
                return ResourceManager.GetString("ArcsineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   arcta. 例: arctan(90) or arctg(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArctangentToolTip {
            get {
                return ResourceManager.GetString("ArctangentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   arsech. 例: arsech(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArsechToolTip {
            get {
                return ResourceManager.GetString("ArsechToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   arsinh. 例: arsinh(90) or arsh(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArsinhToolTip {
            get {
                return ResourceManager.GetString("ArsinhToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   artanh. 例: artanh(90) or arth(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArtanhToolTip {
            get {
                return ResourceManager.GetString("ArtanhToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   式 &apos;{1}&apos;が関数 &apos;{0}&apos;に割り当てられました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssignFunction {
            get {
                return ResourceManager.GetString("AssignFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値 &apos;{1}&apos;が変数 &apos;{0}&apos;に割り当てられました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssignVariable {
            get {
                return ResourceManager.GetString("AssignVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dmitry Kischenko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthorTextBox {
            get {
                return ResourceManager.GetString("AuthorTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新が利用可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AvailableUpdate {
            get {
                return ResourceManager.GetString("AvailableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビット演算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitwiseExpanderHeader {
            get {
                return ResourceManager.GetString("BitwiseExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された数以上の最小の整数を返す例: ceil(5.5555). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CeilToolTip {
            get {
                return ResourceManager.GetString("CeilToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearButtonHeader {
            get {
                return ResourceManager.GetString("ClearButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearScreenTipText {
            get {
                return ResourceManager.GetString("ClearScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearScreenTipTitle {
            get {
                return ResourceManager.GetString("ClearScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリップボード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClipboardGroupHeader {
            get {
                return ResourceManager.GetString("ClipboardGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cm {
            get {
                return ResourceManager.GetString("cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConditionalAndToolTip {
            get {
                return ResourceManager.GetString("ConditionalAndToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件付きOR演算子. 例: x == 0 || y != 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConditionalOrToolTip {
            get {
                return ResourceManager.GetString("ConditionalOrToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConstantsExpanderHeader {
            get {
                return ResourceManager.GetString("ConstantsExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単位変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConverterButtonHeader {
            get {
                return ResourceManager.GetString("ConverterButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   演算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConverterCalculateText {
            get {
                return ResourceManager.GetString("ConverterCalculateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単位変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConverterScreenTipText {
            get {
                return ResourceManager.GetString("ConverterScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単位変換(Ctrl+Alt+C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConverterScreenTipTitle {
            get {
                return ResourceManager.GetString("ConverterScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単位変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConverterTitle {
            get {
                return ResourceManager.GetString("ConverterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Converter Type: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConverterTypeText {
            get {
                return ResourceManager.GetString("ConverterTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解をコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyAnswerMenuItem {
            get {
                return ResourceManager.GetString("CopyAnswerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyButtonHeader {
            get {
                return ResourceManager.GetString("CopyButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   式をコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyExpressionMenuItem {
            get {
                return ResourceManager.GetString("CopyExpressionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された文字列をコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyScreenTipText {
            get {
                return ResourceManager.GetString("CopyScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー (Ctrl+C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyScreenTipTitle {
            get {
                return ResourceManager.GetString("CopyScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   csc. 例: csc(90) or cosec(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CosecantToolTip {
            get {
                return ResourceManager.GetString("CosecantToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cosh. 例: cosh(90) or ch(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CoshToolTip {
            get {
                return ResourceManager.GetString("CoshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cos. 例: cos(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CosineToolTip {
            get {
                return ResourceManager.GetString("CosineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cot. 例: cot(90) or ctg(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CotangentToolTip {
            get {
                return ResourceManager.GetString("CotangentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   coth. 例: coth(90) or cth(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CothToolTip {
            get {
                return ResourceManager.GetString("CothToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   csch. 例: csch(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CschToolTip {
            get {
                return ResourceManager.GetString("CschToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CutButtonHeader {
            get {
                return ResourceManager.GetString("CutButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された文字列を切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CutScreenTipText {
            get {
                return ResourceManager.GetString("CutScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り(Ctrl+X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CutScreenTipTitle {
            get {
                return ResourceManager.GetString("CutScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された変数に値を代入するか、ユーザー関数を作成. 例: x := 1, f(x) := sin(x) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefToolTip {
            get {
                return ResourceManager.GetString("DefToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DegreeButtonHeader {
            get {
                return ResourceManager.GetString("DegreeButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度として度を使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DegreeScreenTipText {
            get {
                return ResourceManager.GetString("DegreeScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   度 (Ctrl+Alt+D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DegreeScreenTipTitle {
            get {
                return ResourceManager.GetString("DegreeScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteExpButtonHeader {
            get {
                return ResourceManager.GetString("DeleteExpButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された文字列を削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteExpScreenTipText {
            get {
                return ResourceManager.GetString("DeleteExpScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteExpScreenTipTitle {
            get {
                return ResourceManager.GetString("DeleteExpScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteMenuItem {
            get {
                return ResourceManager.GetString("DeleteMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行列式. 例: det({{1, 3}, {9, 4}}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DetToolTip {
            get {
                return ResourceManager.GetString("DetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   除算した値を代入. 例: x /= 2. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivAssignToolTip {
            get {
                return ResourceManager.GetString("DivAssignToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   等価演算子. 例: x == 10. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EqualToolTip {
            get {
                return ResourceManager.GetString("EqualToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションを閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExitToolTip {
            get {
                return ResourceManager.GetString("ExitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る (Alt+F4) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExitToolTipTitle {
            get {
                return ResourceManager.GetString("ExitToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   式のリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpListGroupHeader {
            get {
                return ResourceManager.GetString("ExpListGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpressionsTextBox {
            get {
                return ResourceManager.GetString("ExpressionsTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpressionTextBox {
            get {
                return ResourceManager.GetString("ExpressionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   階乗. 例: fact(4) or 4! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FactToolTip {
            get {
                return ResourceManager.GetString("FactToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された数以下の最大の整数を返す. 例: floor(5.55555). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FloorToolTip {
            get {
                return ResourceManager.GetString("FloorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forループ. 例: for(z := z + 1, x := 0, x &lt; 10, x := x + 1). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ForToolTip {
            get {
                return ResourceManager.GetString("ForToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FromText {
            get {
                return ResourceManager.GetString("FromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FuncNameHeader {
            get {
                return ResourceManager.GetString("FuncNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力されたすべての関数をウィンドウに表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FuncScreenTitText {
            get {
                return ResourceManager.GetString("FuncScreenTitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関数 (Ctrl+Alt+F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FuncScreenTitTitle {
            get {
                return ResourceManager.GetString("FuncScreenTitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FunctionButtonHeader {
            get {
                return ResourceManager.GetString("FunctionButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FunctionsTitle {
            get {
                return ResourceManager.GetString("FunctionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FuncValueHeader {
            get {
                return ResourceManager.GetString("FuncValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大公約数. 例: gcd(2, 4) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GCDToolTip {
            get {
                return ResourceManager.GetString("GCDToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グラード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GradianButtonHeader {
            get {
                return ResourceManager.GetString("GradianButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度としてグラードを使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GradianScreenTipText {
            get {
                return ResourceManager.GetString("GradianScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グラード (Ctrl+Alt+G) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GradianScreenTipTitle {
            get {
                return ResourceManager.GetString("GradianScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グラフ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphsTab {
            get {
                return ResourceManager.GetString("GraphsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以上. 例: x &gt;= 10. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GreaterOrEqualToolTip {
            get {
                return ResourceManager.GetString("GreaterOrEqualToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   より大きい. 例: x &gt; 10. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GreaterThanToolTip {
            get {
                return ResourceManager.GetString("GreaterThanToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホームページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HomePageTextBox {
            get {
                return ResourceManager.GetString("HomePageTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HomeRibbonTabHeader {
            get {
                return ResourceManager.GetString("HomeRibbonTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   双曲線 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HyperbolicExpanderHeader {
            get {
                return ResourceManager.GetString("HyperbolicExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分岐条件. 例: if(x &lt; 2, sin(x), cos(x)). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfToolTip {
            get {
                return ResourceManager.GetString("IfToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   おそらく、変数が正しく入力されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexOutOfRangeExceptionError {
            get {
                return ResourceManager.GetString("IndexOutOfRangeExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   逆行列. 例: inverse({{1, 3}, {9, 4}}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InverseToolTip {
            get {
                return ResourceManager.GetString("InverseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小公倍数. 例: lcm(2, 4) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LCMToolTip {
            get {
                return ResourceManager.GetString("LCMToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下. 例: x &lt;= 10. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LessOrEqualToolTip {
            get {
                return ResourceManager.GetString("LessOrEqualToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   より小さい. 例: x &lt; 10. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LessThanToolTip {
            get {
                return ResourceManager.GetString("LessThanToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   常用対数(底 10). 例: lg(3) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LgToolTip {
            get {
                return ResourceManager.GetString("LgToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自然対数(底 e) 例: ln(10) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LnToolTip {
            get {
                return ResourceManager.GetString("LnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   論理式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogicTab {
            get {
                return ResourceManager.GetString("LogicTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対数 &quot;y&quot; of &quot;x&quot;. 例: log(2, 4) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogToolTip {
            get {
                return ResourceManager.GetString("LogToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MathParameterType_Constant {
            get {
                return ResourceManager.GetString("MathParameterType_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MathParameterType_Normal {
            get {
                return ResourceManager.GetString("MathParameterType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込み専用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MathParameterType_ReadOnly {
            get {
                return ResourceManager.GetString("MathParameterType_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MathTab {
            get {
                return ResourceManager.GetString("MathTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MatrixExpanderHeader {
            get {
                return ResourceManager.GetString("MatrixExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   乗算した値を代入. : x *= 2. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MulAssignToolTip {
            get {
                return ResourceManager.GetString("MulAssignToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewMenu {
            get {
                return ResourceManager.GetString("NewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   等しくない. 例: x != 10. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotEqualToolTip {
            get {
                return ResourceManager.GetString("NotEqualToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この演算子はサポートしていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotSupportedOperationError {
            get {
                return ResourceManager.GetString("NotSupportedOperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビットNOT演算子. 有理数は小数点以下切り捨て. 例: not(3) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotToolTip {
            get {
                return ResourceManager.GetString("NotToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   べき乗根. 例: root(27, 3) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NthRootToolTip {
            get {
                return ResourceManager.GetString("NthRootToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   算術 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumberAndArithmeticExpanderHeader {
            get {
                return ResourceManager.GetString("NumberAndArithmeticExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenMenu {
            get {
                return ResourceManager.GetString("OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビットOR演算. 有理数は小数点以下切り捨て. 例: x or y, x | y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OrToolTip {
            get {
                return ResourceManager.GetString("OrToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   式のパラメータ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamGroupHeader {
            get {
                return ResourceManager.GetString("ParamGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasteButtonHeader {
            get {
                return ResourceManager.GetString("PasteButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリップボードから貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasteScreenTipText {
            get {
                return ResourceManager.GetString("PasteScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け (Ctrl+V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasteScreenTipTitle {
            get {
                return ResourceManager.GetString("PasteScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ２乗. 例: 7^2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PowerOfTwoToolTip {
            get {
                return ResourceManager.GetString("PowerOfTwoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   べき乗. 例: 7^4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PowerOfYToolTip {
            get {
                return ResourceManager.GetString("PowerOfYToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総乗. 例: product(式, 乗算の開始, 乗算の終了, 増加量, 変数名) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProductToolTip {
            get {
                return ResourceManager.GetString("ProductToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラミング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgExpanderHeader {
            get {
                return ResourceManager.GetString("ProgExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラジアン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RadianButtonHeader {
            get {
                return ResourceManager.GetString("RadianButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度としてラジアンを使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RadianScreenTipText {
            get {
                return ResourceManager.GetString("RadianScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラジアン(Ctrl+Alt+R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RadianScreenTipTitle {
            get {
                return ResourceManager.GetString("RadianScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   やり直し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedoButtonHeader {
            get {
                return ResourceManager.GetString("RedoButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   直前の変更をやり直す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedoScreenTipText {
            get {
                return ResourceManager.GetString("RedoScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   やり直し(Ctrl+Y) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedoScreenTipTitle {
            get {
                return ResourceManager.GetString("RedoScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値を最も近い整数または指定された桁数に丸める. 例: round(数値, 桁数). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoundToolTip {
            get {
                return ResourceManager.GetString("RoundToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を付けて保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveAsMenu {
            get {
                return ResourceManager.GetString("SaveAsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveMenu {
            get {
                return ResourceManager.GetString("SaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sec. 例: sec(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SecantToolTip {
            get {
                return ResourceManager.GetString("SecantToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sech. 例: sech(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SechToolTip {
            get {
                return ResourceManager.GetString("SechToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default _angle measurement: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAngle {
            get {
                return ResourceManager.GetString("SettingsAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAutoLang {
            get {
                return ResourceManager.GetString("SettingsAutoLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ２進数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsBin {
            get {
                return ResourceManager.GetString("SettingsBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsCancel {
            get {
                return ResourceManager.GetString("SettingsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新の確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsCheckUpdates {
            get {
                return ResourceManager.GetString("SettingsCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   10進数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDec {
            get {
                return ResourceManager.GetString("SettingsDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDegree {
            get {
                return ResourceManager.GetString("SettingsDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グラード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsGradian {
            get {
                return ResourceManager.GetString("SettingsGradian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16進数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHex {
            get {
                return ResourceManager.GetString("SettingsHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Language*: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsLanguageLabel {
            get {
                return ResourceManager.GetString("SettingsLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語はプログラムの再起動後に設定されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsLanguageToolTip {
            get {
                return ResourceManager.GetString("SettingsLanguageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   式の最大数: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMaxNumber {
            get {
                return ResourceManager.GetString("SettingsMaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default _number base: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsNumber {
            get {
                return ResourceManager.GetString("SettingsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8進数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsOct {
            get {
                return ResourceManager.GetString("SettingsOct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラジアン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsRadian {
            get {
                return ResourceManager.GetString("SettingsRadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Remember number base and angle measurement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsRemember {
            get {
                return ResourceManager.GetString("SettingsRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsReset {
            get {
                return ResourceManager.GetString("SettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember right _tool bar state. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsRightToolBar {
            get {
                return ResourceManager.GetString("SettingsRightToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関数を保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsSaveUF {
            get {
                return ResourceManager.GetString("SettingsSaveUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsToolTip {
            get {
                return ResourceManager.GetString("SettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定(Alt+S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsToolTipTitle {
            get {
                return ResourceManager.GetString("SettingsToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsViewTitle {
            get {
                return ResourceManager.GetString("SettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember window state and _position. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindowPos {
            get {
                return ResourceManager.GetString("SettingsWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グリッド線を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowGridCheckBox {
            get {
                return ResourceManager.GetString("ShowGridCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   式を単純化. 例: simplify(arcsin(sin(x))) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimplifyToolTip {
            get {
                return ResourceManager.GetString("SimplifyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sin. 例: sin(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SineToolTip {
            get {
                return ResourceManager.GetString("SineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sinh. 例: sinh(90) or sh(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SinhToolTip {
            get {
                return ResourceManager.GetString("SinhToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平方根. 例: sqrt(9) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SquareRootToolTip {
            get {
                return ResourceManager.GetString("SquareRootToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StandartExpanderHeader {
            get {
                return ResourceManager.GetString("StandartExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   減算した値を代入. 例: x -= 2. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubAssignToolTip {
            get {
                return ResourceManager.GetString("SubAssignToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総和. 例: sum(式, 加算の開始, 加算の終了, 増加量, 変数名) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SumToolTip {
            get {
                return ResourceManager.GetString("SumToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tan. 例: tan(90) or tg(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TangentToolTip {
            get {
                return ResourceManager.GetString("TangentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tanh. Example: tanh(90) or th(90) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TanhToolTip {
            get {
                return ResourceManager.GetString("TanhToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリップボードへ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToClipboardMenuItem {
            get {
                return ResourceManager.GetString("ToClipboardMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToInputMenuItem {
            get {
                return ResourceManager.GetString("ToInputMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolsGroupHeader {
            get {
                return ResourceManager.GetString("ToolsGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToText {
            get {
                return ResourceManager.GetString("ToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行列の転置. 例: transpose({{1, 3}, {9, 4}}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransposeToolTip {
            get {
                return ResourceManager.GetString("TransposeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   三角関数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrigonometricExpanderHeader {
            get {
                return ResourceManager.GetString("TrigonometricExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   真理値表 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TruthTableTab {
            get {
                return ResourceManager.GetString("TruthTableTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関数&apos;{0}&apos;は削除されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndefineFunction {
            get {
                return ResourceManager.GetString("UndefineFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変数&apos;{0}&apos;は削除されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndefineVariable {
            get {
                return ResourceManager.GetString("UndefineVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された変数またはユーザー関数を削除. 例: undef(x) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndefToolTip {
            get {
                return ResourceManager.GetString("UndefToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndoButtonHeader {
            get {
                return ResourceManager.GetString("UndoButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   直前の変更を元に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndoScreenTipText {
            get {
                return ResourceManager.GetString("UndoScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻す(Ctrl+Z) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndoScreenTipTitle {
            get {
                return ResourceManager.GetString("UndoScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Unit: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnitsText {
            get {
                return ResourceManager.GetString("UnitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Value: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueText {
            get {
                return ResourceManager.GetString("ValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変数が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableNotFoundExceptionError {
            get {
                return ResourceManager.GetString("VariableNotFoundExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariablesButtonHeader {
            get {
                return ResourceManager.GetString("VariablesButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariablesTitle {
            get {
                return ResourceManager.GetString("VariablesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VarNameHeader {
            get {
                return ResourceManager.GetString("VarNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力したすべての変数をウィンドウに表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VarScreenTitText {
            get {
                return ResourceManager.GetString("VarScreenTitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変数 (Ctrl+Alt+V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VarScreenTitTitle {
            get {
                return ResourceManager.GetString("VarScreenTitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VarValueHeader {
            get {
                return ResourceManager.GetString("VarValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionTextBox {
            get {
                return ResourceManager.GetString("VersionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whileループ. 例: while(x := x + 1, x &lt; 10). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WhileToolTip {
            get {
                return ResourceManager.GetString("WhileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビットXOR演算子. 有理数は小数点以下切り捨て. 例: x xor y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XOrToolTip {
            get {
                return ResourceManager.GetString("XOrToolTip", resourceCulture);
            }
        }
    }
}
